config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'weather#home'

  post 'forecast', to: 'weather#show'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
# frozen_string_literal: true

# Controller to create the home route for the weather.
class WeatherController < ApplicationController
  def home; end

  def show
    cache_key = { zip_code: params[:zip_code] }
    @cached_data = Rails.cache.exist?(cache_key)
    @forecast = Rails.cache.fetch(cache_key, expires_in: 30.minutes) do
      weather_service = WeatherService.new(params[:zip_code], params[:country])
      WeatherService::Result.new(weather_service.fetch_weather_info)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/weather_helper.rb
# frozen_string_literal: true

module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppleWeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/weather/home.html.erb
<div class="weather-form">
    <%= form_tag forecast_path, method: :post, data: { turbo: false } do  %>
        <%= text_field_tag :zip_code, nil, placeholder: 'Enter a Zip Code' %>
        <%= text_field_tag :country, nil, placeholder: 'Enter a Country Code' %>
        <%= submit_tag 'Submit' %>
    <% end %>
</div>

app/views/weather/show.html.erb
<div>
    <% if @cached_data == true %>
    <h2>The data is coming from cache!</h2>
    <% else %>
    <h2>The data is coming from database!</h2>
    <% end %>
    <h3>Current Temperature: </h3>
    <%= @forecast.current_temp %>&deg;F
    <h3>Low: </h3>
    <%= @forecast.min_temp %>&deg;F
    <h3>High: </h3>
    <%= @forecast.max_temp %>&deg;F
    <h3>Extended Weather Condition: </h3>
    <%= @forecast.weather_condition %>
</div>